# Generated by Django 3.2.10 on 2022-07-12 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=128)),
                ('doctor_name', models.TextField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_1', models.TimeField()),
                ('dosage_1', models.PositiveIntegerField(help_text='Enter dosage quantity for time 1')),
                ('dosage_1_unit', models.IntegerField(choices=[(10, 'tb'), (11, 'ml')], default=10, help_text='tb/ml?')),
                ('time_2', models.TimeField(blank=True)),
                ('dosage_2', models.PositiveIntegerField(help_text='Enter dosage quantity for time 2')),
                ('dosage_2_unit', models.IntegerField(choices=[(10, 'tb'), (11, 'ml')], default=10, help_text='tb/ml?')),
                ('time_3', models.TimeField(blank=True)),
                ('dosage_3', models.PositiveIntegerField(help_text='Enter dosage quantity for time 3')),
                ('dosage_3_unit', models.IntegerField(choices=[(10, 'tb'), (11, 'ml')], default=10, help_text='tb/ml?')),
                ('repeat', models.IntegerField(choices=[(101, 'daily'), (102, 'alternate days'), (103, 'weekly'), (104, 'monthly')], default=101)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_email', models.EmailField(blank=True, help_text='Optional', max_length=254)),
                ('relation_type', models.IntegerField(choices=[(1001, 'friend'), (1002, 'father'), (1003, 'mother'), (1004, 'sister'), (1005, 'brother'), (1006, 'son'), (1007, 'daughter'), (1008, 'husband'), (1009, 'wife'), (1010, 'inlaw'), (1011, 'grandparent'), (1012, 'grandchild'), (1013, 'aunt'), (1014, 'uncle'), (1015, 'cousin')], default=1001)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
