# Generated by Django 3.2.10 on 2022-05-17 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a make(Ex: Ford) ', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Please Enter 2 or more Characters for Make Name')])),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Please Enter 2 or more Characters for Nick Name')])),
                ('mileage', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('make_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.make')),
            ],
        ),
    ]
