# Generated by Django 3.2.10 on 2022-05-21 08:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedName', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator('2', 'Name of the cat breed should be more than 2')])),
            ],
        ),
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=200)),
                ('Weight', models.PositiveIntegerField()),
                ('Foods', models.CharField(max_length=200)),
                ('Breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.breed')),
            ],
        ),
    ]
