# Generated by Django 3.2.10 on 2022-05-24 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breedName',
            field=models.CharField(help_text='Enter an item', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Name of the cat breed should be more than 2')]),
        ),
    ]
